### ISSUE TITLE
Close the repo in preference to project for uiuc-microreactor

### ISSUE THREAD

**Issue by samgdotson** [arfc/uiuc-microreactors#1]
Issue can be closed when repo is closed (or renamed if possible). 
@ZoeRichter maybe have a repo that is dedicated to your particular part of the uiuc-microreactor project?

**Comment by ZoeRichter** [comment]
renamed repo, and will update readme to reflect that this single repository will hold multiple directories, each for a separate reactor concept

**Comment by robfairh** [comment]
@ZoeRichter can you rename the repo? Both the project and the repo have almost the same name. Maybe this one should be something like "Microreactor_documentation" or something alike.

**Comment by ZoeRichter** [comment]
Aren't the other project/repo pairs named similarly?  Like the moltres repo and the moltres project.

**Comment by robfairh** [comment]
Can you add some more description in the readme? I don't completely understand the purpose of this repo. Is this to hold the whole project? If yes, then name it 'uiuc-microreactor' as the project. If this repo is just for the documentation (and that's what I understand by reading the readme), then change its name.

**Comment by ZoeRichter** [comment]
It's holding all data, analysis of specific reactors, and, presumably, any reports made regarding them.  Every time the repo changes its name, everyone has to manually change all of their remotes, and rename their own forks.  I would prefer to rename as little as possible.

**Comment by robfairh** [comment]
Up to you. Can you at least update the readme with that information about the repo? And then you can close the issue.

**Comment by robfairh** [comment]
Closed with #3
