### ISSUE TITLE
bibfile missing?

### ISSUE THREAD

**Issue by katyhuff** [arfc/uiuc-microreactors#14]
I think the bibfile is missing from the repository. This issue can be closed with a pull request that adds a bibfile generated by Zotero from a shared group directory within the arfc group library.

**Comment by mehmeturkmen** [comment]
@katyhuff A bibfile was added. But it was modified by removing the url lines from the original bib file as these lines caused some internal error in the latex.

**Comment by katyhuff** [comment]
When this is the case, close the issue with a reference to the commit, like so:

Closed with #13
